; Folding ranges for Zolo

[
  (function_item)
  (extern_body)
  (extern_group)
  (extern_dependencies)
  (dependencies_declaration)
  (dependency_group)
  (extern_dependency_options)
  (struct_item)
  (enum_item)
  (trait_item)
  (impl_item)
  (macro_item)
  (block)
  (field_declaration_list)
  (enum_variant_list)
  (trait_body)
  (impl_body)
  (declaration_body)
  (compact_field_list)
  (parameter_list)
  (argument_list)
  (array_expression)
  (map_expression)
  (struct_expression_body)
  (match_expression)
  (try_catch_expression)
  (for_expression)
  (while_expression)
  (while_let_expression)
  (loop_expression)
  (lambda_expression)
  (trailing_lambda)
  (every_expression)
  (after_expression)
  (timeout_expression)
  (block_comment)
] @fold

; Ordinary callback bodies own their parameters and braces.
(trailing_callback_body) @fold
